<stmt> ::= <flag> <params>

<flag> ::= "-" <char>+

<char> ::= [0-9a-zA-Z]

<params> ::= <flagParam>* <positionalParam>* <optionalParam>*
           | <flagParam>* <positionalParam>* <positionalParamList>

<positionalParam> ::= "<" <pname> ">"

<optionalParam> ::= "[" <pname> "]"

<flagParam> ::= "[" <flag> <pname>? "]"

<positionalParamList> ::= "<" <pname> ">..."

<pname> ::= [a-zA-Z]+
